repos:
  - repo: local
    hooks:
      - id: nextflow-lint
        name: Lint Nextflow scripts and fix formatting
        entry: nextflow lint
        language: system
        files: '\.nf$|nextflow\.config$'
        exclude: |
          (?x)^(
            validation/.*\.nf$
          )$
        args:
          [
            "-format",
            "-sort-declarations",
            "-spaces",
            "4",
            "-harshil-alignment",
            "-output",
            "concise",
          ]
        pass_filenames: true
        # FIXME Throws `ERROR ~ Unexpected error [ConcurrentModificationException]`
        require_serial: true
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.1.0"
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@3.6.2

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
        exclude: |
          (?x)^(
              .*\.snap$
          )$
      - id: end-of-file-fixer
        exclude: |
          (?x)^(
              .*\.snap$
          )$
