name: star_align
description: "Map sequencing reads to a reference genome with STAR"
keywords:
  - alignment
  - rna-seq
  - star
tools:
  - star:
      description: "STAR is a fast RNA-seq read mapper, with support for splice-junction and fusion read detection"
      homepage: "https://github.com/alexdobin/STAR"
      documentation: "https://physiology.med.cornell.edu/faculty/skrabanek/lab/angsd/lecture_notes/STARmanual.pdf"
      tool_dev_url: "https://github.com/alexdobin/STAR"
      doi: "10.1093/bioinformatics/bts635"
      licence: "MIT"
