name: samtools_view
description: "Filter SAM/BAM files"
keywords:
  - view
  - bam
  - sam
tools:
  - samtools:
      description: "Tools for dealing with SAM, BAM and CRAM files"
      homepage: "http://www.htslib.org/"
      documentation: "http://www.htslib.org/doc/samtools.html"
      tool_dev_url: "https://github.com/samtools/samtools"
      doi: "10.1093/bioinformatics/btp352"
      licence: "MIT"
