name: prek

on:
  pull_request:
  push:
    branches: [main]

jobs:
  prek:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nf-core/setup-nextflow@v2
        with:
          version: "25.10.3"
      - uses: j178/prek-action@v2
