name: Plugin Validation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NFT_VER: "0.9.3"
  NXF_ANSI_LOG: false
  NXF_SINGULARITY_CACHEDIR: ${{ github.workspace }}/.singularity
  NXF_SINGULARITY_LIBRARYDIR: ${{ github.workspace }}/.singularity
jobs:
  validation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v2

      - name: Install nf-test
        uses: nf-core/setup-nf-test@v1
        with:
          install-pdiff: true

      - name: Conda setup
        uses: conda-incubator/setup-miniconda@505e6394dae86d6a5c7fbb6e3fb8938e3e863830 # v3
        with:
          auto-update-conda: true
          conda-remove-defaults: true

      - name: Clean workspace
        run: make clean

      - name: Set NFT_WORKDIR dynamically
        run: echo "NFT_WORKDIR=~" >> $GITHUB_ENV

      - name: Build and validate plugin
        run: make validate

      - name: Upload validation artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: validation-results
          path: |
            validation/*/work/pipeline_info/
            validation/*/work/*.log
            validation/*/work/.nextflow.log
            validation/.nf-test/reports/
            validation/**/*.nf.test.snap
          retention-days: 7

      - name: Upload test logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: validation-logs
          path: |
            validation/*/.nextflow.log
            validation/*/work/**/*.log
            validation/.nf-test/**/*.log
          retention-days: 7
