name: Plugin Validation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "11"

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v2

      - name: Install nf-test
        uses: nf-core/setup-nf-test@v1
        with:
          install-pdiff: true

      - name: Clean workspace
        run: make clean

      - name: Build and validate plugin
        run: make validate

      - name: Upload validation artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: validation-results
          path: |
            validation/*/work/pipeline_info/
            validation/*/work/*.log
            validation/*/work/.nextflow.log
            validation/.nf-test/reports/
            validation/**/*.nf.test.snap
          retention-days: 7

      - name: Upload test logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: validation-logs
          path: |
            validation/*/.nextflow.log
            validation/*/work/**/*.log
            validation/.nf-test/**/*.log
          retention-days: 7
